name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
autolabeler:
    - label: "type: enhancement"
      branch: '/feature\/.+/'
    - label: "type: bug"
      branch: '/(bug)?fix\/.+/'
      title: "/fix/i"
    - label: "type: docs"
      files: "*.rst"
      branch: '/docs{0,1}\/.+/'
    - label: "type: devops"
      branch: '/devops\/.+/'
categories:
    - title: "Enhancements"
      labels: "type: enhancement"
    - title: "Bug Fixes"
      labels: "type: bug"
    - title: "Documentation"
      label: "type: docs"
    - title: "DevOps"
      label: "type: devops"
change-template: "- $TITLE by @$AUTHOR in $URL"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels:
    - "skip-changelog"
version-resolver:
    major:
        labels:
            - "major"
    minor:
        labels:
            - "minor"
    patch:
        labels:
            - "patch"
    default: patch
template: |
    ## $RESOLVED_VERSION

    $CHANGES

    **Full Changelog**: https://github.com/xCDAT/xcdat/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
