exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [commit]
fail_fast: true

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml

    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
          - id: black

    - repo: https://github.com/timothycrosley/isort
      rev: 5.11.4
      hooks:
          - id: isort

    # Need to use flake8 GitHub mirror due to CentOS git issue with GitLab
    # https://github.com/pre-commit/pre-commit/issues/1206
    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            args: ["--config=setup.cfg"]
            additional_dependencies: [flake8-isort]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.990
      hooks:
          - id: mypy
            args: ["--config=setup.cfg"]
            additional_dependencies:
                [
                    dask==2022.10.2,
                    numpy==1.23.5,
                    pandas==1.5.3,
                    xarray==2023.1.0,
                    types-python-dateutil==2.8.19,
                ]
