# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
    os: "ubuntu-20.04"
    tools:
        python: "mambaforge-4.10"
    jobs:
        post_create_environment:
            # Use conda run executable wrapper to set all env variables, including ESMFMKFILE.
            # Source: https://github.com/readthedocs/readthedocs.org/issues/5339#issuecomment-1576603529
            - conda run -n ${CONDA_DEFAULT_ENV} pip install . --no-deps

# Build documentation in the docs/ directory with Sphinx
sphinx:
    configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
    - pdf

conda:
    environment: conda-env/dev.yml
