blank_issues_enabled: true
contact_links:
    - name: Usage question (xCDAT)
      url: https://github.com/xCDAT/xcdat/discussions
      about: |
          Ask questions and discuss with other xCDAT community members here. Please
          browse the xCDAT Discussions Forum or xCDAT documentation first before asking a
          question to make sure it is not already answered. If you can't find an
          answer, please include a self-contained reproducible example with your
          question if possible. Thanks!

    - name: Usage question (xarray)
      url: https://github.com/pydata/xarray/discussions
      about: |
          If your questions or discussions are related to xarray, please visit this page
          to reach out to xarray community members.
