name: Feature Request
description: Suggest an idea for xCDAT
title: "[FEATURE]: "
labels: ["Type: Enhancement"]
assignees: []
body:
    - type: checkboxes
      id: feature-request-criteria
      attributes:
        label: Feature Request Criteria
        Description: First, please make sure your feature request meets the following criteria.
        options:
          - label: Feature is not implemented by ``xarray``
            required: true
          - label: Feature is not implemented by another actively developed xarray-based package
            required: true
          - label: Feature is not limited to specific use cases (e.g., data quality issues)
            required: true
          - label: Feature is generally reusable
            required: true
          - label: Feature is relatively simple and lightweight to implement and use
            required: true

    - type: textarea
      id: description
      attributes:
          label: Is your feature request related to a problem?
          description: |
              Please do a quick search of existing issues to make sure that this has not been asked before.
              Please provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Describe the solution you'd like
          description: |
              A clear and concise description of what you want to happen.

    - type: textarea
      id: alternatives
      attributes:
          label: Describe alternatives you've considered
          description: |
              A clear and concise description of any alternative solutions or features you've considered.
      validations:
          required: false

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: |
              Add any other context about the feature request here.
      validations:
          required: false
