name: Feature Request
description: Suggest an idea for xCDAT
title: "[FEATURE]: "
labels: ["Type: Enhancement"]
assignees: []
body:
    - type: checkboxes
      id: Feature Criteria
      attributes:
      label: First, please make sure your feature request meets the following criteria.
      options:
        - label: Is not implemented or can be handled natively by ``xarray``
        - label: Is not implemented by another actively developed xarray-based package
        - label: Is not specific to limited use cases (e.g., data quality issues)
        - label: Is generally reusable
        - label: Is relatively simple and lightweight to implement and use
      validations:
        required: true

    - type: textarea
      id: description
      attributes:
          label: Is your feature request related to a problem?
          description: |
              Please do a quick search of existing issues to make sure that this has not been asked before.
              Please provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Describe the solution you'd like
          description: |
              A clear and concise description of what you want to happen.

    - type: textarea
      id: alternatives
      attributes:
          label: Describe alternatives you've considered
          description: |
              A clear and concise description of any alternative solutions or features you've considered.
      validations:
          required: false

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: |
              Add any other context about the feature request here.
      validations:
          required: false
