# A conda development environment with all dependencies, including optional and documentation dependencies.
name: xcdat_dev
channels:
    - conda-forge
    - defaults
dependencies:
    # Base - required for building the package.
    # =========================================
    - python >=3.10
    - setuptools
    - cf_xarray >=0.10.3
    - cftime
    - dask
    - netcdf4
    - numpy >=2.0.0,<3.0.0
    - pandas
    - python-dateutil
    - scipy
    - xarray >=2024.03.0
    - xesmf >=0.8.7
    - xgcm
    # Optional - enables additional features.
    # =========================================
    - matplotlib-base >=3.8.4
    - nc-time-axis >=1.4.1
    # Documentation
    # ==================
    - sphinx
    - sphinx-autosummary-accessors
    - sphinx-book-theme
    - sphinx-copybutton
    - nbsphinx
    - sphinx-design
    - pandoc
    - ipython # Required for nbsphinx syntax highlighting
    - gsw-xarray # Required for vertical regridding example
    - pooch # Required for xarray tutorial data
    # Quality Assurance
    # ==================
    - types-python-dateutil
    # NOTE: If the tools below are updated, also update their 'rev' in `.pre-commit.config.yaml`
    - pre-commit=4.1.0
    - ruff=0.9.4
    - mypy=1.14.1
    # Testing
    # ==================
    - pytest
    - pytest-cov
    # Developer Tools
    # ==================
    - jupyterlab
    - tbump
