{% set version = "0.1.0" %}

package:
    name: xcdat
    version: {{ version }}

source:
  git_url: https://github.com/tomvothecoder/xcdat.git
  git_rev: v{{ version }}

build:
    noarch: python
    number: 0
    script: python -m pip install . --no-deps --force-reinstall -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - typing_extensions
    - cartopy
    - matplotlib
    - netcdf4
    - xarray
    - typing_extensions

test:
  imports:
    - xcdat
    - xcdat.axis
    - xcdat.climatology

about:
    home: https://github.com/tomvothecoder/xcdat
    license: MIT
    summary: 'Xarray Extended with Climate Data Analysis Tools'
    dev_url: https://github.com/tomvothecoder/xcdat
    doc_url: https://tomvothecoder.github.io/xcdat
    doc_source_url: https://github.com/tomvothecoder/xcdat/tree/main/docs
